/**
 * Core mechanism geometry.
 *
 * Coordinate system (right-handed):
 *   +X = Right, -X = Left, +Y = Up, -Y = Down, +Z = Front (towards the viewer), -Z = Back.
 *
 * Every cubie of the 3×3×3 mechanism has a "home" position with integer
 * coordinates in {-1, 0, 1}. The ENTIRE state of a cubie is one proper rotation
 * R (an element of the 24-element rotation group of the cube): the cubie that
 * started at `home` now sits at `R · home`, physically turned by R. Because every
 * face turn is a rotation about the origin, this is exact – position and
 * orientation can never drift apart.
 */

export type Vec3 = readonly [number, number, number];
/** Row-major 3×3 integer matrix. */
export type Mat3 = readonly number[];

export const dot = (a: Vec3, b: Vec3): number => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];
export const cross = (a: Vec3, b: Vec3): Vec3 => [
  a[1] * b[2] - a[2] * b[1],
  a[2] * b[0] - a[0] * b[2],
  a[0] * b[1] - a[1] * b[0],
];
export const vecEq = (a: Vec3, b: Vec3): boolean => a[0] === b[0] && a[1] === b[1] && a[2] === b[2];
export const vecKey = (v: Vec3): string => `${v[0]},${v[1]},${v[2]}`;
export const scale = (v: Vec3, s: number): Vec3 => [v[0] * s, v[1] * s, v[2] * s];
export const add = (a: Vec3, b: Vec3): Vec3 => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];

export function matMul(a: Mat3, b: Mat3): Mat3 {
  const r = new Array<number>(9);
  for (let i = 0; i < 3; i++)
    for (let j = 0; j < 3; j++) {
      let s = 0;
      for (let k = 0; k < 3; k++) s += a[i * 3 + k] * b[k * 3 + j];
      r[i * 3 + j] = s;
    }
  return r;
}
export function matVec(m: Mat3, v: Vec3): Vec3 {
  return [
    m[0] * v[0] + m[1] * v[1] + m[2] * v[2],
    m[3] * v[0] + m[4] * v[1] + m[5] * v[2],
    m[6] * v[0] + m[7] * v[1] + m[8] * v[2],
  ];
}
export const transpose = (m: Mat3): Mat3 => [m[0], m[3], m[6], m[1], m[4], m[7], m[2], m[5], m[8]];
const IDENTITY: Mat3 = [1, 0, 0, 0, 1, 0, 0, 0, 1];

/**
 * Clockwise quarter turn as seen from OUTSIDE, looking at a face with outward
 * normal n (n is a unit axis vector). This is a rotation of -90° about n:
 *   R v = -(n × v) + n (n · v)
 */
export function clockwiseQuarterAbout(n: Vec3): Mat3 {
  const cols: Vec3[] = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
  ].map((e) => {
    const v = e as unknown as Vec3;
    const c = cross(n, v);
    const d = dot(n, v);
    return [-c[0] + n[0] * d, -c[1] + n[1] * d, -c[2] + n[2] * d] as Vec3;
  });
  // columns -> row-major
  return [cols[0][0], cols[1][0], cols[2][0], cols[0][1], cols[1][1], cols[2][1], cols[0][2], cols[1][2], cols[2][2]];
}

// ---------------------------------------------------------------------------
// The 24-element rotation group, generated by closure. Index 0 = identity.
// ---------------------------------------------------------------------------
const matKey = (m: Mat3) => m.join(',');

function generateRotations(): Mat3[] {
  const gens = [clockwiseQuarterAbout([1, 0, 0]), clockwiseQuarterAbout([0, 1, 0]), clockwiseQuarterAbout([0, 0, 1])];
  const list: Mat3[] = [IDENTITY];
  const seen = new Set([matKey(IDENTITY)]);
  for (let i = 0; i < list.length; i++)
    for (const g of gens) {
      const m = matMul(g, list[i]);
      const k = matKey(m);
      if (!seen.has(k)) {
        seen.add(k);
        list.push(m);
      }
    }
  if (list.length !== 24) throw new Error('rotation group generation failed');
  return list;
}

export const ROTATIONS: readonly Mat3[] = generateRotations();
const ROT_INDEX = new Map(ROTATIONS.map((m, i) => [matKey(m), i]));
export const ROT_IDENTITY = 0;

export function rotIndexOf(m: Mat3): number {
  const i = ROT_INDEX.get(matKey(m));
  if (i === undefined) throw new Error('not a cube rotation: ' + m.join(','));
  return i;
}
/** ROT_COMPOSE[a][b] = index of (R_a · R_b): apply b first, then a. */
export const ROT_COMPOSE: readonly (readonly number[])[] = ROTATIONS.map((a) => ROTATIONS.map((b) => rotIndexOf(matMul(a, b))));
export const ROT_INVERSE: readonly number[] = ROTATIONS.map((m) => rotIndexOf(transpose(m)));
export const rotApply = (r: number, v: Vec3): Vec3 => matVec(ROTATIONS[r], v);

// ---------------------------------------------------------------------------
// Faces of the MECHANISM (turning layers). Order is fixed: U R F D L B.
// ---------------------------------------------------------------------------
export const FACE_NAMES = ['U', 'R', 'F', 'D', 'L', 'B'] as const;
export type FaceName = (typeof FACE_NAMES)[number];
export const FACE_NORMALS: readonly Vec3[] = [
  [0, 1, 0],
  [1, 0, 0],
  [0, 0, 1],
  [0, -1, 0],
  [-1, 0, 0],
  [0, 0, -1],
];
export const FACE_AXIS = [1, 0, 2, 1, 0, 2] as const;
export const FACE_SIGN = [1, 1, 1, -1, -1, -1] as const;
export const OPPOSITE_FACE = [3, 4, 5, 0, 1, 2] as const;
export const FACE_LONG_NAMES = ['Up', 'Right', 'Front', 'Down', 'Left', 'Back'] as const;
/** Rotation index of a clockwise quarter turn of each face. */
export const FACE_QUARTER_ROT: readonly number[] = FACE_NORMALS.map((n) => rotIndexOf(clockwiseQuarterAbout(n)));

export function faceOfNormal(n: Vec3): number {
  const i = FACE_NORMALS.findIndex((f) => vecEq(f, n));
  if (i < 0) throw new Error('not a face normal');
  return i;
}

// ---------------------------------------------------------------------------
// Cubies. ids 0-7 corners, 8-19 edges, 20-25 centers.
// Corner/edge order follows the conventional Kociemba ordering so that the
// E-slice edges (FR, FL, BL, BR) are edges 8-11.
// ---------------------------------------------------------------------------
export type CubieType = 'corner' | 'edge' | 'center';

export const CORNER_NAMES = ['URF', 'UFL', 'ULB', 'UBR', 'DFR', 'DLF', 'DBL', 'DRB'] as const;
export const EDGE_NAMES = ['UR', 'UF', 'UL', 'UB', 'DR', 'DF', 'DL', 'DB', 'FR', 'FL', 'BL', 'BR'] as const;
export const CENTER_NAMES = FACE_NAMES;

const CORNER_HOMES: Vec3[] = [
  [1, 1, 1],
  [-1, 1, 1],
  [-1, 1, -1],
  [1, 1, -1],
  [1, -1, 1],
  [-1, -1, 1],
  [-1, -1, -1],
  [1, -1, -1],
];
const EDGE_HOMES: Vec3[] = [
  [1, 1, 0],
  [0, 1, 1],
  [-1, 1, 0],
  [0, 1, -1],
  [1, -1, 0],
  [0, -1, 1],
  [-1, -1, 0],
  [0, -1, -1],
  [1, 0, 1],
  [-1, 0, 1],
  [-1, 0, -1],
  [1, 0, -1],
];

export const NUM_CUBIES = 26;
export const CORNER_IDS = [0, 1, 2, 3, 4, 5, 6, 7];
export const EDGE_IDS = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19];
export const CENTER_IDS = [20, 21, 22, 23, 24, 25];
export const E_SLICE_EDGE_IDS = [16, 17, 18, 19];

export const HOME: readonly Vec3[] = [...CORNER_HOMES, ...EDGE_HOMES, ...FACE_NORMALS];
export const CUBIE_TYPE: readonly CubieType[] = HOME.map((h) => {
  const nz = h.filter((c) => c !== 0).length;
  return nz === 3 ? 'corner' : nz === 2 ? 'edge' : 'center';
});
export const CUBIE_CODE: readonly string[] = [...CORNER_NAMES, ...EDGE_NAMES, ...CENTER_NAMES];

/** A "slot" is a position in space; slot i is the home position of cubie i. */
const SLOT_BY_POS = new Map(HOME.map((h, i) => [vecKey(h), i]));
export function slotOfPosition(p: Vec3): number {
  const s = SLOT_BY_POS.get(vecKey(p));
  if (s === undefined) throw new Error('not a cubie position: ' + p.join(','));
  return s;
}

/** Rotations that carry cubie `c`'s home onto slot `s` (empty if types differ). */
export function rotationsCarrying(c: number, s: number): number[] {
  const out: number[] = [];
  for (let r = 0; r < 24; r++) if (vecEq(rotApply(r, HOME[c]), HOME[s])) out.push(r);
  return out;
}
